events {}
http {
    types {
        text/html html;
        text/css css;
        application/javascript js;
    }
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate example.csr;
        ssl_certificate_key example.key;

        location / {
            root .;
            index index.html;
        }
    }
}